name: custom action workflow

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: Your project name
        required: true
      email:
        description: Your email id
        required: true

jobs:
  build:
    # The type of runner that the job will run on, this job will run on ubuntu machine
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
      # Install Cookie cutter
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Installing cookiecutter
        id: install_cookie_cutter
        run: pip3 install cookiecutter
      # Run cookie cutter
      - name: Running cookiecutter
        id: running_cookie_cutter
        run: |
          cookiecutter . --no-input \
            project_name="${{ github.event.inputs.project_name }}" \
            email="${{ github.event.inputs.email }}"
          mv $project_name/* .
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
            add: .
            message: "template updated"
            default_author: github_actions
