name: custom action workflow

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: Your project name
        required: true
      email:
        description: Your email id
        required: true

jobs:
  build:
    # The type of runner that the job will run on, this job will run on ubuntu machine
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
      # Install Cookie cutter
      - name: Installing cookiecutter
        id: install_cookie_cutter
        run: pip3 install cookiecutter
      # Run cookie cutter
      - name: Running cookiecutter
        id: running_cookie_cutter
        run: |
          # Run cookiecutter
          pushd /tmp
          cookiecutter gh:akbarsha03/testtemplate --no-input \
            project_name=$(${{ github.event.inputs.project_name }}) \
            email="$(${{ github.event.inputs.email }})"
          popd
          # Move generated content to root directory of repo
          mv /tmp/$REPO_NAME/* .
          # And .gitignore too:
          mv /tmp/$REPO_NAME/.gitignore .
          # Delete the setup.yml workflow, it has served its purpose
          rm .github/workflows/setup.yml